services:
  proxmox:
    hostname: pve
    build:
      context: ..
      args:
        VERSION_ARG: "0.0.1"
        PRODUCT_NAME: Tailnet Proxmox
        SUPPORT_URL: https://github.com/mayas-alas/tailnet-proxmox
    image: ghcr.io/mayas-alas/tailnet-proxmox:0.0.1
    container_name: proxmox
    environment:
      PASSWORD: "root"
    ports:
      - 8006:8006
    volumes:
      - ./data:/var/lib/vz
      - ./config:/var/lib/pve-cluster
    privileged: true
    restart: on-failure
    stop_grace_period: 2m
